#!/usr/bin/env python3
"""Emit tables (md + tex) and figures for round-2 experiments E1-E3."""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
OUT = HERE / "experiments_round2"
FIGS = HERE / "figures"
FIGS.mkdir(exist_ok=True)
PAPER = HERE / "paper"

plt.rcParams.update({
    'font.family': 'serif', 'font.size': 9,
    'axes.labelsize': 10, 'axes.titlesize': 10,
    'xtick.labelsize': 7.5, 'ytick.labelsize': 7.5, 'legend.fontsize': 7.5,
    'figure.dpi': 300, 'savefig.bbox': 'tight', 'savefig.pad_inches': .02})

E1 = json.loads((OUT / "e1_selection_procedures.json").read_text())
E2 = json.loads((OUT / "e2_matched_teacher.json").read_text())
E3 = json.loads((OUT / "e3_cost_quality.json").read_text())

# RECORDED serving latency (generated_dynamic_beta_runtime_macros.tex)
RUNTIME = {"Video_Games": {"gate_us": 1.171, "post_us": 85.89,
                           "expert_ms": 3.710, "total_ms": 3.796}}
DOMS = ["Video_Games", "Baby_Products", "Diginetica_HID"]
SHORT = {"Video_Games": "Video", "Baby_Products": "Baby",
         "Diginetica_HID": "Diginetica"}


# --------------------------------------------------------------------- E1
def emit_e1() -> None:
    md = ["# E1 — Selection-procedure comparison (test R@20)\n",
          "| Procedure | Val. cells | OOF fit | Video | Baby | Diginetica |",
          "|---|---|---|---|---|---|"]
    tex = [r"% Auto-generated by emit_round2_tables.py",
           r"\begin{table}[t]\centering\scriptsize",
           r"\caption{Selection-procedure comparison. `Val.\ cells' counts"
           r" configurations evaluated on declared-validation labels during"
           r" \emph{selection}; the fifteen allocation controls are"
           r" \emph{audit-only} variants never used to select the primary"
           r" gate, whose configuration (three-feature linear,"
           r" $\Delta_{\rm eff}{=}.10$) is fixed in advance on all domains."
           r" Test R@20 and regret against the test-side oracle (upper"
           r" bound over the audit family) follow.}",
           r"\label{tab:round2-procedures}",
           r"\setlength{\tabcolsep}{2.6pt}",
           r"\resizebox{\textwidth}{!}{%",
           r"\begin{tabular}{lcc rrr rrr}", r"\hline",
           r"& & & \multicolumn{3}{c}{Test R@20} & \multicolumn{3}{c}{Regret vs.\ oracle}\\",
           r"Procedure & Val.\ cells & OOF fit & Video & Baby & Digi. & Video & Baby & Digi.\\",
           r"\hline"]
    order = list(E1["domains"][DOMS[0]]["procedures"].keys())
    pretty = {
        "P1 endpoint-only (best of memory/neural)":
            ("P1 endpoint-only", "2", r"--"),
        "P2 global-beta fusion (training-learned)":
            ("P2 global-$\\beta$ fusion", "0", "1 scalar"),
        "P3 regime router (short/long)":
            ("P3 regime router", "0", "2 scalars"),
        "P4 oracle over gate family (upper bound)":
            ("P4 oracle (audit family)", r"test-side", r"--"),
        "P5 forced neural inclusion (fusion-only best)":
            ("P5 forced neural incl.", "0", "as P6"),
        "P6 query-conditioned gate (primary)":
            ("P6 query-cond.\\ gate", "0", "5-param gate"),
    }
    for proc in order:
        label, val_cells, oof_fit = pretty[proc]
        cells_r, cells_g = [], []
        for dom in DOMS:
            p = E1["domains"][dom]["procedures"][proc]
            cells_r.append(f"{p['r20']:.5f}")
            cells_g.append(f"{p['regret_vs_oracle']:.5f}")
        md.append(f"| {label.replace('$\\\\beta$','β').replace('\\\\ ',' ')} "
                  f"| {val_cells} | {oof_fit} | " + " | ".join(cells_r) +
                  " | " + " | ".join(cells_g) + " |")
        tex.append(f"{label} & {val_cells} & {oof_fit} & " +
                   " & ".join(cells_r) + " & " + " & ".join(cells_g) + r"\\")
    tex += [r"\hline", r"\end{tabular}}", r"\end{table}"]
    md += [
        "",
        "Audit-only variants: 15 allocation-control policies (buckets, "
        "feature gates, deltas, reassignment). The primary gate is not "
        "selected from them. 'Zero validation cells' refers to selection "
        "only: P2 still fits one scalar and P6 five parameters on the "
        "4,000-row OOF calibration set.",
        "",
        "**Fusion vs best endpoint, per seed (recomputed from frozen arrays):** "
        "Video 3/3 seeds, Baby 3/3 seeds (Diginetica endpoint arrays were "
        "lost in the incident; recorded means show memory .49428 > neural "
        ".44852 while fusion .51701).",
        "",
        "**Dynamic minus OOF-global ΔU [95% CI] (recorded paired bootstrap):**",
        "| Domain | ΔU | 95% CI |", "|---|---|---|"]
    for dom in DOMS:
        d = E1["domains"][dom]
        md.append(f"| {SHORT[dom]} | {d['dU_dynamic_minus_global']:+.5f} | "
                  f"[{d['dU_ci95'][0]:+.5f}, {d['dU_ci95'][1]:+.5f}] |")
    md += ["",
           "**Finding (report as-is):** the single training-learned global β "
           "(P2, zero validation cells) is within .00025 R@20 of the 15-cell "
           "test-side oracle on every domain. The query-conditioned gate adds a "
           "detectable-but-tiny +.0002 U on Video (CI above zero) and is "
           "statistically undetectable on Baby and Diginetica. Endpoint-only "
           "selection (P1) loses .008–.023. Forbidding component rejection "
           "(P5) costs nothing here because fusion beats both endpoints on "
           "all domains and seeds."]
    (OUT / "e1_selection_procedures.md").write_text("\n".join(md))
    (PAPER / "round2_procedures.tex").write_text("\n".join(tex))


# --------------------------------------------------------------------- E2
def emit_e2() -> None:
    md = ["# E2 — Matched-information comparison\n",
          "## Same-teacher conditions (recorded; TF-IDF condition)\n",
          "| Condition | Init | Video | Baby |", "|---|---|---|---|"]
    tex = [r"% Auto-generated by emit_round2_tables.py",
           r"\begin{table}[t]\centering\small",
           r"\caption{Matched-information and expert-swap controls (test"
           r" R@20). Upper block: recorded TF--IDF condition for \emph{both}"
           r" arms; Video's main-table teacher is E5-small, so the .14700/"
           r".05600 CEARF-N rows are the TF--IDF-condition runs, not the"
           r" main system of Table~\ref{tab:allocation-main}. Lower block:"
           r" ID-only NARM replacing PASGR inside the identical"
           r" memory/gate/fusion stack (3 seeds).}",
           r"\label{tab:round2-matched}",
           r"\setlength{\tabcolsep}{4pt}",
           r"\begin{tabular}{llrr}", r"\hline",
           r"Condition & Init & Video & Baby\\", r"\hline",
           r"NARM (ID-only) & random & .13705 & .02990\\",
           r"CEARF-N no-meta & random & .13208 & .05055\\",
           r"NARM+sem & TF--IDF & \textbf{.15387} & \textbf{.06628}\\",
           r"CEARF-N (TF--IDF condition) & TF--IDF & .14700 & .05600\\",
           r"\hline",
           r"\multicolumn{4}{l}{\emph{Neural-expert swap (PASGR $\to$ NARM),"
           r" same memory+gate}}\\",
           r"NARM-only & ID & .13763 & .03880\\",
           r"gate fusion over NARM & ID & .14854 & .05001\\",
           r"fusion gain & & +.01091 & +.01121\\",
           r"\hline", r"\end{tabular}", r"\end{table}"]
    cond = [("NARM (ID-only)", "random",
             E2["domains"]["Video_Games"]["matched_teacher"]["narm_id"],
             E2["domains"]["Baby_Products"]["matched_teacher"]["narm_id"]),
            ("CEARF-N no-meta", "random",
             E2["domains"]["Video_Games"]["matched_teacher"]["cearfn_nometa"],
             E2["domains"]["Baby_Products"]["matched_teacher"]["cearfn_nometa"]),
            ("NARM+sem", "TF-IDF",
             E2["domains"]["Video_Games"]["matched_teacher"]["narm_sem"],
             E2["domains"]["Baby_Products"]["matched_teacher"]["narm_sem"]),
            ("CEARF-N (TF-IDF condition)", "TF-IDF",
             E2["domains"]["Video_Games"]["matched_teacher"]["cearfn_full"],
             E2["domains"]["Baby_Products"]["matched_teacher"]["cearfn_full"])]
    for name, init, v, b in cond:
        md.append(f"| {name} | {init} | {v:.5f} | {b:.5f} |")
    md += ["",
           "## Expert swap — does fusion help a STRONG expert too? "
           "(recorded, 3 seeds)\n",
           "| Domain | NARM-only | Gate fusion | Gain |", "|---|---|---|---|"]
    for dom in DOMS:
        d = E2["domains"][dom]
        md.append(f"| {SHORT[dom]} | {d['expert_swap']['narm_only']:.5f} | "
                  f"{d['expert_swap']['dynamic']:.5f} | "
                  f"+{d['swap_fusion_gain_over_narm_only']:.5f} |")
    md += ["",
           "NOTE: the rescue/damage counts (4451/1766, 3889/1191, 3076/1693) "
           "belong to the PRIMARY comparison (dynamic fusion vs memory-only) "
           "and satisfy (rescue−damage)/N = ΔR@20 vs memory exactly; they are "
           "NOT a decomposition of the NARM-swap gain."]
    (OUT / "e2_matched_teacher.md").write_text("\n".join(md))
    (PAPER / "round2_matched.tex").write_text("\n".join(tex))


# --------------------------------------------------------------------- E3
# RECORDED same-lineage values (generated_dynamic_beta_baseline_audit.tex for
# baselines; generated_dynamic_beta_full_metrics.tex for fused allocations).
# The v2/evidence MRR recomputation stays in the artifact package only —
# different lineage, kept out of the main tables by design.
BL = {  # method: (budget label, R20 V, R20 B, R20 D, nDCG20 D)
    "Transition-only": ("det.", .04223, .00735, .40102, .16687),
    "V-SKNN": ("8", .11936, .05038, .50506, .25184),
    "STAN": ("16", .12115, .04944, .51502, .25952),
    "GRU4Rec": (r"$\leq$12 ep.", .10368, .04501, .41785, .19557),
    "NARM": (r"$\leq$12 ep.", .13705, .02990, .53406, .26321),
    "SR-GNN": (r"$\leq$5 ep.", .12267, .05208, .49267, .23599),
    "SIGMA-compat.": (r"$\leq$10 ep.", .08644, .02473, .37219, .17374),
    r"\method{} (equal $.5$)": ("0 (alloc.)", .14610, .05555, .51430, .25658),
    r"\method{} (OOF global)": ("0 (alloc.)", .14719, .05671, .51702, .25786),
    r"\method{} (dynamic gate)": ("0 (alloc.)", .14735, .05669, .51701,
                                  .25792),
}


def emit_e3() -> None:
    md = ["# E3 — Cost-quality audit (same lineage as Tables 1-2)\n",
          "| Method | Budget | R@20 V | R@20 B | R@20 D | nDCG@20 D |",
          "|---|---|---|---|---|---|"]
    tex = [r"% Auto-generated by emit_round2_tables.py",
           r"\begin{table}[t]\centering\scriptsize",
           r"\caption{Cost--quality audit, same lineage as"
           r" Tables~\ref{tab:allocation-main} and \ref{tab:baselines}:"
           r" baselines from the audited grids, fused rows from the"
           r" dynamic-$\beta$ runs. `Budget' = declared-validation cells"
           r" used for selection (allocation needs none; expert budgets are"
           r" upstream). CEARF-N serving latency recorded on Apple M2 Pro"
           r" (warm). MRR for the separate v2 lineage is kept in the"
           r" artifact package only.}",
           r"\label{tab:round2-cost}",
           r"\setlength{\tabcolsep}{3pt}",
           r"\resizebox{\textwidth}{!}{%",
           r"\begin{tabular}{l rrrr r}", r"\hline",
           r"Method & Budget & R@20 (V) & R@20 (B) & R@20 (D) & nDCG@20 (D)\\",
           r"\hline"]
    for meth, (budget, v, b, d, nd) in BL.items():
        md.append(f"| {meth.replace(chr(92)+'method{}','CEARF-N')} | "
                  f"{budget.replace('$\\leq$','<=').replace(chr(92)+' ',' ')} "
                  f"| {v:.5f} | {b:.5f} | {d:.5f} | {nd:.5f} |")
        tex.append(f"{meth} & {budget} & {v:.5f} & {b:.5f} & {d:.5f} & "
                   f"{nd:.5f}" + r"\\")
    rt = RUNTIME["Video_Games"]
    tex += [r"\hline",
            r"\multicolumn{6}{l}{\emph{Serving (Video, recorded): gate "
            f"{rt['gate_us']}$\\mu$s + fusion {rt['post_us']}$\\mu$s"
            f" = 2.3\\% of {rt['total_ms']}" +
            "ms/query; expert retrieval dominates.}}\\\\",
            r"\end{tabular}}", r"\end{table}"]
    md += ["",
           f"**CEARF-N serving decomposition (recorded, Video):** gate "
           f"{rt['gate_us']} µs + fusion {rt['post_us']} µs + expert "
           f"{rt['expert_ms']} ms = {rt['total_ms']} ms/query — gate+fusion "
           "overhead is 2.3% of total; expert retrieval dominates.",
           "",
           "**Note:** per-baseline latency cannot be re-measured after the "
           "incident (datasets lost); the recorded figure "
           "`figures/fig_latency.pdf` remains the reference chart.",
           "",
           "v2-lineage MRR@20 (recomputed from frozen arrays) lives in "
           "`experiments_round2/mrr_from_arrays.json` — different lineage, "
           "excluded from the main tables deliberately."]
    (OUT / "e3_cost_quality.md").write_text("\n".join(md))
    (PAPER / "round2_cost.tex").write_text("\n".join(tex))


# ------------------------------------------------------------------ figures
def figs() -> None:
    # E1: procedure bars with oracle line
    fig, axes = plt.subplots(1, 3, figsize=(10.5, 3.0))
    order = list(E1["domains"][DOMS[0]]["procedures"].keys())
    labels = ["P1 endpoint", "P2 global-β", "P3 regime", "P4 oracle",
              "P5 forced", "P6 gate"]
    colors = ['#b2182b', '#2166ac', '#92c5de', '#333333', '#f4a582',
              '#4dac26']
    for ax, dom in zip(axes, DOMS):
        ps = E1["domains"][dom]["procedures"]
        vals = [ps[k]["r20"] for k in order]
        oracle = ps["P4 oracle over gate family (upper bound)"]["r20"]
        x = np.arange(len(vals))
        bars = ax.bar(x, vals, .62, color=colors, edgecolor='white',
                      linewidth=.5)
        ax.axhline(oracle, color='#333', linestyle='--', linewidth=.9)
        lo, hi = min(vals), max(vals)
        pad = (hi - lo) * .5 + 1e-4
        ax.set_ylim(lo - pad, hi + pad * .35)
        for b, v in zip(bars, vals):
            ax.text(b.get_x() + b.get_width() / 2, v, f'{v:.4f}',
                    ha='center', va='bottom', fontsize=5.4, rotation=90)
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=45, ha='right', fontsize=6.5)
        ax.set_title(SHORT[dom], fontweight='bold')
        ax.grid(axis='y', alpha=.25, linewidth=.5)
        ax.set_axisbelow(True)
    axes[0].set_ylabel('Test R@20')
    fig.tight_layout()
    fig.savefig(FIGS / 'fig_e1_procedures.pdf')
    fig.savefig(FIGS / 'fig_e1_procedures.png', dpi=150)
    plt.close(fig)

    # E2: matched-teacher + swap
    fig, axes = plt.subplots(1, 2, figsize=(9.0, 3.0))
    ax = axes[0]
    conds = ['NARM\n(ID)', 'CEARF-N\n(no-meta)', 'NARM+sem\n(TF-IDF)',
             'CEARF-N\n(full)']
    vg = [.13705, .13208, .15387, .147]
    bp = [.02990, .05055, .06628, .056]
    x = np.arange(4)
    w = .38
    ax.bar(x - w / 2, vg, w, label='Video', color='#2166ac',
           edgecolor='white', linewidth=.5)
    ax.bar(x + w / 2, bp, w, label='Baby', color='#f4a582',
           edgecolor='white', linewidth=.5)
    ax.set_xticks(x)
    ax.set_xticklabels(conds, fontsize=7)
    ax.set_ylabel('R@20')
    ax.set_title('(a) Matched-information conditions', fontweight='bold',
                 fontsize=9)
    ax.legend(frameon=False)
    ax.grid(axis='y', alpha=.25, linewidth=.5)
    ax.set_axisbelow(True)
    ax = axes[1]
    doms3 = ['Video', 'Baby', 'Diginetica']
    narm_only = [E2["domains"][d]["expert_swap"]["narm_only"] for d in DOMS]
    fused = [E2["domains"][d]["expert_swap"]["dynamic"] for d in DOMS]
    x = np.arange(3)
    ax.bar(x - w / 2, narm_only, w, label='NARM expert alone',
           color='#bababa', edgecolor='white', linewidth=.5)
    ax.bar(x + w / 2, fused, w, label='gate fusion (same stack)',
           color='#2166ac', edgecolor='white', linewidth=.5)
    for xi, (n, f) in enumerate(zip(narm_only, fused)):
        ax.text(xi + w / 2, f, f'+{f - n:.4f}', ha='center', va='bottom',
                fontsize=6)
    ax.set_xticks(x)
    ax.set_xticklabels(doms3, fontweight='bold')
    ax.set_title('(b) Expert swap: fusion over strong NARM',
                 fontweight='bold', fontsize=9)
    ax.legend(frameon=False, loc='upper left')
    ax.grid(axis='y', alpha=.25, linewidth=.5)
    ax.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(FIGS / 'fig_e2_matched.pdf')
    fig.savefig(FIGS / 'fig_e2_matched.png', dpi=150)
    plt.close(fig)

    # E3: quality vs budget scatter + latency decomposition
    fig, axes = plt.subplots(1, 2, figsize=(9.5, 3.0))
    ax = axes[0]
    budget_num = {"V-SKNN": 8, "STAN": 16, "CEARF-N gate family": 15}
    markers = {'Video_Games': 'o', 'Baby_Products': 's',
               'Diginetica_HID': '^'}
    for dom in DOMS:
        xs, ys, ms = [], [], []
        for meth, m in E3["domains"][dom]["methods"].items():
            b = m["tuning_budget"]
            if isinstance(b, int):
                xs.append(b)
                ys.append(m["r20_mean"])
                ms.append(meth)
        ax.scatter(xs, ys, marker=markers[dom], s=28,
                   label=SHORT[dom], alpha=.85, edgecolor='white',
                   linewidth=.4)
        for x0, y0, name in zip(xs, ys, ms):
            if name in ('CEARF-N', 'NARM', 'STAN', 'V-SKNN'):
                ax.annotate(name.replace('_native', ''), (x0, y0),
                            textcoords='offset points', xytext=(4, 3),
                            fontsize=5.8)
    ax.set_xlabel('Validation budget (cells)')
    ax.set_ylabel('Test R@20')
    ax.set_title('(a) Quality vs tuning budget', fontweight='bold',
                 fontsize=9)
    ax.legend(frameon=False)
    ax.grid(alpha=.25, linewidth=.5)
    ax.set_axisbelow(True)
    ax = axes[1]
    comps = ['gate', 'fusion', 'expert\nretrieval']
    vid = E3["domains"]["Video_Games"]["cearfn_serving_latency"]
    baby = E3["domains"]["Baby_Products"]["cearfn_serving_latency"]
    digi = E3["domains"]["Diginetica_HID"]["cearfn_serving_latency"]
    vals = np.array([[vid['gate_us'] / 1000, vid['post_us'] / 1000,
                      vid['expert_ms']],
                     [baby['gate_us'] / 1000, baby['post_us'] / 1000,
                      baby['expert_ms']],
                     [digi['gate_us'] / 1000, digi['post_us'] / 1000,
                      digi['expert_ms']]])
    x = np.arange(3)
    w = .26
    for i, (dom, c) in enumerate(zip(DOMS,
                                     ['#92c5de', '#2166ac', '#08306b'])):
        ax.bar(x + (i - 1) * w, vals[i], w, label=SHORT[dom], color=c,
               edgecolor='white', linewidth=.5)
    ax.set_yscale('log')
    ax.set_xticks(x)
    ax.set_xticklabels(comps, fontsize=7.5)
    ax.set_ylabel('ms/query (log)')
    ax.set_title('(b) CEARF-N serving decomposition', fontweight='bold',
                 fontsize=9)
    ax.legend(frameon=False)
    ax.grid(axis='y', alpha=.25, linewidth=.5)
    ax.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(FIGS / 'fig_e3_cost_quality.pdf')
    fig.savefig(FIGS / 'fig_e3_cost_quality.png', dpi=150)
    plt.close(fig)


if __name__ == '__main__':
    emit_e1()
    emit_e2()
    emit_e3()
    figs()
    print("emitted: 3 md + 3 tex + 3 figures into",
          OUT, PAPER, FIGS, sep='\n  ')
