#!/usr/bin/env python3
"""Integrate backbone-swap + baseline results into paper LaTeX tables.

Reads (incrementally usable; missing seeds are simply absent):
  sparse_bench/paper_baseline_results.json  (BERT4Rec rows, RetailRocket)
  sparse_bench/backbone_swap_results.json   (multi-backbone gate audit)

Writes:
  paper/backbone_swap.tex   multi-backbone gate audit (the C2 table)
  paper/retailrocket.tex    4th-domain main table
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
PAPER = HERE / "paper"

DOM_PRETTY = {"Video_Games": "Video", "Baby_Products": "Baby",
              "Diginetica_HID": "Diginetica",
              "RetailRocket_Large": "RetailRocket"}


def mean_std(values):
    vals = np.asarray(values, dtype=float)
    if len(vals) == 0:
        return None
    if len(vals) == 1:
        return float(vals[0]), None
    return float(vals.mean()), float(vals.std(ddof=1))


def fmt(ms):
    if ms is None:
        return "--"
    m, s = ms
    if s is None:
        return f"{m:.5f}"
    return f"{m:.5f} ({s:.5f})"


def baseline_rows() -> dict:
    path = HERE / "paper_baseline_results.json"
    if not path.exists():
        return {}
    raw = json.loads(path.read_text())
    out = {}
    for domain, domain_block in raw.items():
        models = domain_block.get("models", domain_block)
        for model, block in models.items():
            if not isinstance(block, dict) or "runs" not in block:
                continue
            r20 = [run["test"]["recall@20"] for run in block["runs"]
                   if "test" in run]
            if r20:
                out.setdefault(domain, {})[model] = mean_std(r20)
    return out


def swap_table() -> None:
    path = HERE / "backbone_swap_results.json"
    if not path.exists():
        print("no swap results yet")
        return
    res = json.loads(path.read_text())
    tex = [r"% Auto-generated by emit_backbone_tables.py",
           r"\begin{table}[t]\centering\scriptsize",
           r"\caption{Backbone expert swap inside the identical"
           r" memory/gate/fusion stack (test R@20, mean over seeds)."
           r" Fixed mean-$\beta$ applies the gate's average weight"
           r" uniformly; reassigned averages three deterministic"
           r" permutations of the same $\beta_q$ multiset. The"
           r" dynamic$-$reassigned gap isolates query-level assignment.}",
           r"\label{tab:backbone-swap}",
           r"\setlength{\tabcolsep}{2.6pt}",
           r"\resizebox{\textwidth}{!}{%",
           r"\begin{tabular}{llrrrrrr}", r"\hline",
           r"Domain & Backbone & Expert & Fixed .5 & OOF global &"
           r" Mean-$\beta$ & Reassigned & Dynamic gate\\",
           r"\hline"]
    md = ["# Backbone swap audit\n",
          "| Domain | Backbone | Expert | Fixed .5 | OOF global | "
          "Mean-b | Reassigned | Dynamic |", "|---|---|---|---|---|---|---|---|"]
    for domain_key, block in sorted(res.items()):
        domain = domain_key.split("::")[0]
        for backbone, seeds in sorted(block.get("backbones", {}).items()):
            cols = {k: [] for k in ("expert_only", "fixed_half",
                                    "oof_global", "fixed_mean_beta",
                                    "dynamic")}
            reass = []
            for run in seeds.values():
                cols["expert_only"].append(
                    run["expert_only"]["recall@20"])
                cols["fixed_half"].append(run["fixed_half"]["recall@20"])
                cols["oof_global"].append(run["oof_global"]["recall@20"])
                cols["fixed_mean_beta"].append(
                    run["fixed_mean_beta"]["recall@20"])
                cols["dynamic"].append(run["dynamic"]["recall@20"])
                reass.append(np.mean([x["recall@20"]
                                      for x in run["reassigned_beta"]]))
            row = [fmt(mean_std(cols[k])) for k in
                   ("expert_only", "fixed_half", "oof_global",
                    "fixed_mean_beta")]
            row.append(fmt(mean_std(reass)))
            row.append(fmt(mean_std(cols["dynamic"])))
            tex.append(f"{DOM_PRETTY.get(domain, domain)} & {backbone} & "
                       + " & ".join(row) + r"\\")
            md.append(f"| {DOM_PRETTY.get(domain, domain)} | {backbone} | "
                      + " | ".join(row) + " |")
    tex += [r"\hline", r"\end{tabular}}", r"\end{table}"]
    (PAPER / "backbone_swap.tex").write_text("\n".join(tex))
    (HERE / "experiments_round2" / "backbone_swap.md").write_text(
        "\n".join(md))
    print("wrote paper/backbone_swap.tex")


def retailrocket_table() -> None:
    rows = baseline_rows()
    dom = "RetailRocket_Large"
    if dom not in rows:
        print("no RetailRocket results yet")
        return
    tex = [r"% Auto-generated by emit_backbone_tables.py",
           r"\begin{table}[t]\centering\scriptsize",
           r"\caption{Fourth-domain protocol: RetailRocket-Large"
           r" (repeat-consumption; split declared before any model run)."
           r" Test R@20, mean (sd) over three seeds.}",
           r"\label{tab:retailrocket}",
           r"\begin{tabular}{lr}", r"\hline", r"Method & R@20\\",
           r"\hline"]
    order = ["GRU4Rec", "NARM", "SASRec", "BERT4Rec"]
    for model in order:
        if model in rows[dom]:
            tex.append(f"{model} & {fmt(rows[dom][model])}" + r"\\")
    tex += [r"\hline", r"\end{tabular}", r"\end{table}"]
    (PAPER / "retailrocket.tex").write_text("\n".join(tex))
    print("wrote paper/retailrocket.tex")


if __name__ == "__main__":
    swap_table()
    retailrocket_table()
