#!/usr/bin/env python3
"""Aggregate the fixed-beta RRF-versus-CombSUM operator control."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from summarize_dynamic_beta import _discrete_bootstrap, _per_query_value


HERE = Path(__file__).resolve().parent
DOMAINS = ("Video_Games", "Baby_Products", "Diginetica_HID")
LABELS = {
    "Video_Games": "Video",
    "Baby_Products": "Baby",
    "Diginetica_HID": "Diginetica",
}
METRICS = (
    "recall@6",
    "ndcg@6",
    "recall@10",
    "ndcg@10",
    "recall@20",
    "ndcg@20",
    "utility",
)


def mean_std(values) -> dict:
    array = np.asarray(list(values), dtype=np.float64)
    return {
        "mean": float(array.mean()),
        "std": float(array.std(ddof=1)) if len(array) > 1 else 0.0,
        "values": [float(value) for value in array],
    }


def paired_query_summary(
        runs: list[dict],
        metric: str,
        repetitions: int,
        seed: int,
        baseline: str = "weighted_rrf",
        challenger: str = "normalized_combsum",
) -> dict:
    differences = []
    reference_keys = None
    for run in runs:
        with np.load(run["rank_artifact"], allow_pickle=False) as saved:
            keys = np.asarray(saved["test_keys"], dtype=str)
            if reference_keys is None:
                reference_keys = keys
            elif not np.array_equal(reference_keys, keys):
                raise ValueError("fusion-control test query order differs")
            control = _per_query_value(
                saved[f"test_{challenger}_rank"], metric)
            primary = _per_query_value(
                saved[f"test_{baseline}_rank"], metric)
            differences.append(control - primary)
    query_seed_mean = np.mean(np.stack(differences), axis=0)
    output = _discrete_bootstrap(
        query_seed_mean, repetitions, seed)
    output.update({
        "metric": metric,
        "challenger": challenger,
        "baseline": baseline,
        "seeds": [int(run["seed"]) for run in runs],
        "aggregation": (
            "per-query difference averaged across matched seeds, "
            "then paired query-level bootstrap; conditional on fitted seeds"
        ),
    })
    return output


def summarize_domain(
        block: dict,
        repetitions: int,
) -> dict:
    runs = sorted(block["runs"], key=lambda run: int(run["seed"]))
    if not runs:
        raise ValueError("fusion-control domain has no completed runs")
    aggregate = {}
    methods = (
        "weighted_rrf",
        "normalized_combsum",
        "fixed_05_weighted_rrf",
        "fixed_05_normalized_combsum",
    )
    for method in methods:
        aggregate[method] = {
            metric: mean_std(
                run["test"]["metrics"][method][metric] for run in runs)
            for metric in METRICS
        }
    paired_metrics = ("recall@6", "recall@20", "ndcg@20", "utility")
    paired = {
        "dynamic": {
            metric: paired_query_summary(
                runs,
                metric,
                repetitions,
                20260729 + index,
            )
            for index, metric in enumerate(paired_metrics)
        },
        "fixed_05": {
            metric: paired_query_summary(
                runs,
                metric,
                repetitions,
                20260829 + index,
                baseline="fixed_05_weighted_rrf",
                challenger="fixed_05_normalized_combsum",
            )
            for index, metric in enumerate(paired_metrics)
        },
    }
    return {
        "seeds": [int(run["seed"]) for run in runs],
        "n_seeds": len(runs),
        "aggregate": aggregate,
        "paired": paired,
    }


def tex_number(value: float) -> str:
    return f"{value:.5f}".replace("0.", ".").replace("-0.", "-.")


def tex_mean_sd(value: dict) -> str:
    mean = tex_number(value["mean"])
    if len(value["values"]) <= 1:
        return mean
    return f"{mean} ({tex_number(value['std'])})"


def tex_delta(value: dict) -> str:
    low, high = value["cluster_bootstrap_ci95"]
    rendered = (
        f"{value['difference']:+.5f} "
        f"[{low:+.5f},{high:+.5f}]"
    )
    return rendered.replace("+0.", "+.").replace("-0.", "-.")


def write_tex(summary: dict, destination: Path) -> None:
    rows = [
        "% Generated by summarize_dynamic_beta_fusion_control.py.",
        "\\begin{table}[h]",
        (
            "\\caption{Fusion-operator perturbation under the frozen dynamic "
            "$\\beta_q$ and parameter-free $\\beta=.5$. Values are mean "
            "(SD) over matched seeds. Intervals are paired query-level 95\\% "
            "bootstrap intervals for normalized CombSUM minus weighted RRF.}"
        ),
        "\\label{tab:fusion-operator}",
        "\\centering\\scriptsize",
        "\\setlength{\\tabcolsep}{2pt}",
        "\\begin{tabular}{llrrr}",
        "\\toprule",
        (
            "Domain & Allocation & RRF R@20 & CombSUM R@20 & "
            "$\\Delta$R@20 [95\\% CI]\\\\"
        ),
        "\\midrule",
    ]
    for domain in DOMAINS:
        block = summary["domains"][domain]
        for label, key, rrf, combsum in (
            (
                r"Dynamic $\beta_q$",
                "dynamic",
                "weighted_rrf",
                "normalized_combsum",
            ),
            (
                r"$\beta=.5$",
                "fixed_05",
                "fixed_05_weighted_rrf",
                "fixed_05_normalized_combsum",
            ),
        ):
            rows.append(
                f"{LABELS[domain]} & {label} & "
                f"{tex_mean_sd(block['aggregate'][rrf]['recall@20'])} & "
                f"{tex_mean_sd(block['aggregate'][combsum]['recall@20'])} & "
                f"{tex_delta(block['paired'][key]['recall@20'])}\\\\"
            )
    rows.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\par\\smallskip\\scriptsize The table reports the R@20 control "
        "used for the fusion-operator claim; no claim depends on omitted "
        "cutoffs.",
        "\\end{table}",
        "",
    ])
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(rows))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=HERE / "dynamic_beta_fusion_operator_control.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=HERE / "dynamic_beta_fusion_operator_summary.json",
    )
    parser.add_argument(
        "--tex-output",
        type=Path,
        default=(
            HERE / "paper"
            / "generated_dynamic_beta_fusion_control.tex"
        ),
    )
    parser.add_argument("--bootstrap-repetitions", type=int, default=20_000)
    args = parser.parse_args()
    raw = json.loads(args.input.read_text())
    missing = [domain for domain in DOMAINS
               if domain not in raw.get("domains", {})]
    if missing:
        raise ValueError(f"missing fusion-control domains: {missing}")
    summary = {
        "source": str(args.input),
        "protocol": raw["protocol"],
        "bootstrap_unit": (
            "smallest recoverable test-query identifier; all matched-seed "
            "outcomes carried jointly"
        ),
        "seed_aggregation": (
            "per-query differences averaged over the observed fitted seeds "
            "before bootstrap; intervals condition on those seeds"
        ),
        "domains": {
            domain: summarize_domain(
                raw["domains"][domain], args.bootstrap_repetitions)
            for domain in DOMAINS
        },
    }
    seed_sets = {
        tuple(block["seeds"]) for block in summary["domains"].values()
    }
    if len(seed_sets) != 1:
        raise ValueError("fusion-control domains use different seed sets")
    args.output.write_text(json.dumps(summary, indent=2))
    write_tex(summary, args.tex_output)
    print(args.output)
    print(args.tex_output)


if __name__ == "__main__":
    main()
