#!/usr/bin/env python3
"""Aggregate the NARM expert-swap audit and emit an auditable TeX table."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


HERE = Path(__file__).resolve().parent
DOMAINS = ("Video_Games", "Baby_Products", "Diginetica_HID")
PROTOCOL = "dynamic-beta-narm-expert-swap-v2-full-refit"
EXPECTED_SEEDS = {42, 123, 456}
LABELS = {
    "Video_Games": "Video",
    "Baby_Products": "Baby",
    "Diginetica_HID": "Diginetica",
}
METHODS = ("neural_only", "oof_global", "dynamic")


def aggregate(values: list[float]) -> dict:
    array = np.asarray(values, dtype=np.float64)
    return {
        "mean": float(array.mean()),
        "std": float(array.std(ddof=1)) if len(array) > 1 else 0.0,
        "values": [float(value) for value in array],
    }


def render_cell(block: dict) -> str:
    mean = f"{block['mean']:.5f}".replace("0.", ".")
    if len(block["values"]) == 1:
        return mean
    std = f"{block['std']:.5f}".replace("0.", ".")
    return f"{mean} ({std})"


def summarize(raw: dict, seeds: set[int] | None) -> dict:
    output = {
        "protocol": PROTOCOL,
        "domains": {},
    }
    for domain in DOMAINS:
        domain_block = raw.get(domain, {})
        if domain_block.get("protocol") != PROTOCOL:
            raise ValueError(f"{domain}: unexpected expert-swap protocol")
        runs = [
            run for run in domain_block.get("runs", ())
            if seeds is None or int(run["seed"]) in seeds
        ]
        runs.sort(key=lambda run: int(run["seed"]))
        if not runs:
            raise ValueError(f"no completed expert-swap runs for {domain}")
        actual_seeds = {int(run["seed"]) for run in runs}
        expected_seeds = seeds if seeds is not None else EXPECTED_SEEDS
        if actual_seeds != expected_seeds:
            raise ValueError(
                f"{domain}: expected seeds {sorted(expected_seeds)}, "
                f"got {sorted(actual_seeds)}"
            )
        output["domains"][domain] = {
            "seeds": [int(run["seed"]) for run in runs],
            "n_seeds": len(runs),
            "recall@20": {
                method: aggregate([
                    float(run["test"]["metrics"][method]["recall@20"])
                    for run in runs
                ])
                for method in METHODS
            },
            "utility": {
                method: aggregate([
                    float(run["test"]["metrics"][method]["utility"])
                    for run in runs
                ])
                for method in METHODS
            },
            "dynamic_minus_global": {
                metric: aggregate([
                    float(run["test"]["dynamic_minus_global"][metric])
                    for run in runs
                ])
                for metric in ("recall@6", "recall@20", "utility")
            },
        }
    return output


def write_tex(summary: dict, destination: Path) -> None:
    seed_count = min(
        block["n_seeds"] for block in summary["domains"].values())
    seed_phrase = (
        "one completed seed"
        if seed_count == 1
        else "three completed seeds"
        if seed_count == 3
        else f"{seed_count} completed seeds"
    )
    rows = [
        "% Generated by summarize_dynamic_beta_expert_swap.py.",
        "\\begin{table}[h]",
        (
            "\\caption{ID-only NARM expert swap. Values are test R@20 "
            f"mean (SD) over {seed_phrase}. The CEARF "
            "memory, OOF split, continuous objective, bounded gate, and "
            "$k=20$ are held fixed; the test expert is freshly refit on "
            "complete training sessions.}"
        ),
        "\\label{tab:narm-swap}",
        "\\centering\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{llrrr}",
        "\\toprule",
        "Domain & Neural expert & Neural-only & OOF global & Dynamic $\\beta_q$\\\\",
        "\\midrule",
    ]
    for index, domain in enumerate(DOMAINS):
        block = summary["domains"][domain]["recall@20"]
        rows.append(
            f"{LABELS[domain]} & NARM (ID-only) & "
            f"{render_cell(block['neural_only'])} & "
            f"{render_cell(block['oof_global'])} & "
            f"{render_cell(block['dynamic'])}\\\\"
        )
        if index != len(DOMAINS) - 1:
            rows.append("\\midrule")
    rows.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(rows))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input", type=Path,
        default=HERE / "dynamic_beta_expert_swap_results.json")
    parser.add_argument(
        "--output", type=Path,
        default=HERE / "dynamic_beta_expert_swap_summary.json")
    parser.add_argument(
        "--tex-output", type=Path,
        default=HERE / "paper" / "generated_dynamic_beta_expert_swap.tex")
    parser.add_argument("--seeds", nargs="*", type=int)
    args = parser.parse_args()
    raw = json.loads(args.input.read_text())
    summary = summarize(raw, set(args.seeds) if args.seeds else None)
    args.output.write_text(json.dumps(summary, indent=2))
    write_tex(summary, args.tex_output)
    print(args.output)
    print(args.tex_output)


if __name__ == "__main__":
    main()
